### ISSUE TITLE
Gene names in IMA dataset

### ISSUE THREAD

**Issue by zhuizhui-jj** [snap-stanford/UCE#11]
Your method is very innovative, and the cell features obtained have wide applications in downstream tasks. We downloaded the data from the IMA dataset through the provided link but noticed that gene names are represented by numbers. Could you please provide a dictionary mapping these numbers to the corresponding gene names?

**Comment by Yanay1** [comment]
Thanks!

For the IMA dataset, the .X slot is the UCE embeddings. There are no gene names / expression data in that anndata.

**Comment by fengzhanying** [comment]
Could you please also provide the gene expression data that generated IMA_sample.h5ad?
