### ISSUE TITLE
Location of human protein embeddings 

### ISSUE THREAD

**Issue by vinettey** [snap-stanford/UCE#15]
Hi! I was trying to embed a human dataset using the eval_single_anndata.py. However, in file data_proc/gene_embeddings.py, the directory for protein embeddings (model_files/protein_embeddings/) does not seem to exist. Could you help pointing out where the human embedding file Homo_sapiens.GRCh38.gene_symbol_to_embedding_ESM2.pt. can be found or dowloaded? Thank you!

**Comment by Yanay1** [comment]
It should be automatically downloaded and unzipped when you first run the script, but otherwise you should be able to  download it from here: https://figshare.com/ndownloader/files/42715213
