### ISSUE TITLE
Mismatch error when running UCE on ESM embedding of a new species.

### ISSUE THREAD

**Issue by vinettey** [snap-stanford/UCE#16]
Hi! I encountered a mismatch error when running UCE on ESM embedding of a new species.
RuntimeError: Error(s) in loading state_dict for TransformerModel: size mismatch for pe_embedding.weight: copying a param with shape torch.Size([145469, 5120]) from checkpoint, the shape in current model is torch.Size([19910, 5120]).

I generated protein embeddings with the ESM2 model by the following codes:
<img width="907" alt="Screen Shot 2024-01-21 at 8 41 31 AM" src="https://github.com/snap-stanford/UCE/assets/25111089/ba32f36e-4eda-422e-ba65-8b449561be5d">
Could you please help checking what might went wrong here? Thanks!

**Comment by Yanay1** [comment]
Are you using the most up to data version of the repo? Were you able to walk through [the notebook on embedding new species]( https://github.com/snap-stanford/UCE/blob/main/data_proc/Create%20New%20Species%20Files.ipynb)?

**Comment by vinettey** [comment]
Yes! I was able to walk through the notebook and generate the files.

**Comment by vinettey** [comment]
This is the command to launch UCE.
<img width="1160" alt="Screen Shot 2024-01-22 at 10 19 25 AM" src="https://github.com/snap-stanford/UCE/assets/25111089/710bc193-69ec-4986-919a-329fee9156a6">

**Comment by Yanay1** [comment]
Can you upload a screenshot of the full error you get when you try to run that? Thanks!

**Comment by vinettey** [comment]
This is the error meesage output by running UCE.

<img width="1499" alt="Screen Shot 2024-01-23 at 3 43 13 PM" src="https://github.com/snap-stanford/UCE/assets/25111089/d0cf96d8-a1b2-407a-b783-3e50649106b0">

**Comment by Yanay1** [comment]
Are you sure you are using the most recent version of the repo? Did you modify the model files at all?

In the current code we added:

```
 empty_pe = torch.zeros(145469, 5120)
  empty_pe.requires_grad = False
  model.pe_embedding = nn.Embedding.from_pretrained(empty_pe)
  model.load_state_dict(torch.load(args.model_loc, map_location="cpu"),
                        strict=True)
```

So I'm not sure how there can be a mismatch to the model there. Maybe try redownloading the model?

**Comment by vinettey** [comment]
Hi! Updating to the latest github solves the problem of the dimension mismatch. But it gives another error on embedding generated for a new species. 
<img width="1484" alt="Screen Shot 2024-01-26 at 3 30 11 PM" src="https://github.com/snap-stanford/UCE/assets/25111089/1bd00270-09fb-4eb7-9280-848a346bd4eb">

**Comment by Yanay1** [comment]
Please see the response here: https://github.com/snap-stanford/UCE/issues/18#issuecomment-1910796722 

This error happens when there is a cell with 0 genes expressed.

**Comment by vinettey** [comment]
Hi! I checked my gene x cell matrix and there's no cells with 0 genes. Could you share the exact code of generating ESM protein embeddings for a new species? I want to make sure there's no mismatch in gene names. Thanks!

**Comment by Yanay1** [comment]
If you look at the UCE output in terminal when processing the dataset, it will output the number of genes matched.

You can also call 

`torch.load("path to the protein embedding dataset")`

to load in the protein embedding dataset which will list the gene names that are filtered.

**Comment by vinettey** [comment]
Thanks for the suggestion! I found the cause for this problem. The wrong adata file was used in the first place (X contains scaled data not count) and the intermediate file was not updated after correcting the adata file.  Thank you again for the help!
