### ISSUE TITLE
Understanding data integration

### ISSUE THREAD

**Issue by maestriev** [snap-stanford/UCE#19]
Very nice work!  

Let's say we embedded 5 scRNA-seq datasets separately with UCE's 33 layer model. 

Do we need to subset so all 5 datasets have the exact same genes in their matrix prior to tokenizing so they will be directly comparable in the UCE space? 

If our goal was to integrate datasets in the UCE space (e.g. generate a plot similar to your integrated Mega-scale Atlas but with less datasets) by creating a UMAP could you please provide some code you used ? (I know tabula sapiens v2 is not available yet, just curious to understand the process). Example: Fig. 1B/2B

Could you share how you generated the integrated UMAPs? Did you run each dataset through UCE separately to get the zero-shot embeddings, then concatenate all the .h5ad's now containing the "X_uce" slot and then run scany's default. Would something like this be appropriate:

```
#merge the 5 datasets into a single adata

#then use the X_uce slot for the integrated umap
sc.pp.neighbors(adata, use_rep='X_uce') 
sc.tl.umap(adata)
```

**Comment by Yanay1** [comment]
Thanks!

For UCE you should not do any gene subsetting. That includes not doing any highly variable gene selection.

After embedding the datasets separately, you can then merge them into one dataset using `anndata.concat`.

After that, the code you provided to calculate the UMAP would be correct (calculating neighbors on the `'X_uce'` space).

**Comment by Lee951108** [comment]
Hi, in the process of data integration, I encountered an issue. When integrating different h5ad files, following your guidance, I first embedded each file separately. Then, I used ad.concat to merge the data together. However, the same gene obtained 1028 values separately during embedding. How should I handle this during concatenation？The default is to retain the embedding values from the first file.

**Comment by Yanay1** [comment]
How are you concatenating the anndatas?

Could you clarify what you mean by the same gene having 1028 different values?

To combine anndatas, I usually do something like this:

`joint_ad = anndata.concat({"dataset_1":ad_1, "dataset_2":ad_2.....}, label="dataset")`

**Comment by Lee951108** [comment]
I found that the first gene is the same by checking each adata.var['name'], and then I checked the corresponding data in adata.obsm['X_uce']. Afterwards, when I used merge_list = [adata1, adata2, adata3] and adatas = ad.concat(merge_list) to merge them, I found that the data in adatas.obsm['X_uce'] is the same as adata1. So, I am considering how to handle it when merging for genes that are common to each dataset. Also, I constructed UMAP using X_uce based on your previous answer, and the result is as shown in the figure. Could you please advise where the problem might be?
![Adata3_UMAP](https://github.com/snap-stanford/UCE/assets/139623315/5be16bf3-5496-43c3-bf4d-9485c8ed1afd)

**Comment by Yanay1** [comment]
What is the exact command that you are running? What are the shapes of the individual anndatas and then the shape of the joined adata?

**Comment by Lee951108** [comment]
the .concat code question
`adata1 = sc.read_h5ad('GSE123013_uce_adata.h5ad')
adata2 = sc.read_h5ad('GSE114615_uce_adata.h5ad')
adata3 = sc.read_h5ad('GSE158761_uce_adata.h5ad')
merge_list = [adatal,adata2,adata3]
adatas = ad.concat(merge_list)
`
![1](https://github.com/snap-stanford/UCE/assets/139623315/c4d4b2c5-fc83-418a-a83c-28bc6d999356)
![2](https://github.com/snap-stanford/UCE/assets/139623315/3829bd36-a06e-430e-9298-aa4d50ca4704)
![3](https://github.com/snap-stanford/UCE/assets/139623315/d2db7370-766a-4026-8014-eaa5a33415d1)

the individual umap 
` sc.pp.neighbors(adata3,use_rep='X_uce')
sc.tl.umap(adata3)
 sc.pl.umap(adata3,color = 'labels')
`
![Adata3_UMAP](https://github.com/snap-stanford/UCE/assets/139623315/cf0ac407-21ec-4c66-b206-42bb8532ab57)
the joined umap 
`sc.pp.neighbors(adatas,use_rep='X_uce') 
sc.tl.umap(adatas)
sc.pl.umap(adatas,color = 'labels') `
![adatas](https://github.com/snap-stanford/UCE/assets/139623315/5d68823b-e965-4ef6-b6d8-1d561db08b80)

**Comment by Yanay1** [comment]
Sorry I am not sure I understand what the issue is.

When you concatenate anndatas they are stacked in the order of the list you created. So the first cell in the merged anndata should have that highlighted UCE value.

**Comment by Yanay1** [comment]
I don't see that there are three copies of that gene in those screenshots in the joint anndata? In `adatas.var` there should only be one copy of that gene.
