### ISSUE TITLE
About New Species

### ISSUE THREAD

**Issue by zhonghuaxiaodangjiayo** [snap-stanford/UCE#20]
Hello! Quite an exciting job. Here I have some questions to ask: I noticed that the cellular representation of green monkeys is embedded in your article, but green monkeys are not in your training species and there is no protein embedding for that species available in ESM2. Did you run an ESM2 model of the green monkey for it, or did you set the species to human？

**Comment by Yanay1** [comment]
Hi!

We included green monkey (as well as naked mole rat and chicken) as examples of UCE's ability to embed new species that were not in the training data.

To embed a new species not in the training data, please follow the example in the vignette here: (https://github.com/snap-stanford/UCE/blob/main/data_proc/Create%20New%20Species%20Files.ipynb)

You can find ESM2 protein embeddings, including that of Green Monkey (the genome/proteome used is named 'Chlorocebus sabaeus') here: https://drive.google.com/drive/folders/1_Dz7HS5N3GoOAG6MdhsXWY1nwLoN13DJ

If there is a new species not included there that you would like protein embeddings for I'd be happy to create it and upload it. You can also follow the instructions here: https://github.com/snap-stanford/SATURN/blob/main/protein_embeddings/Generate%20Protein%20Embeddings.ipynb if you wish to create new protein embeddings yourself.

**Comment by Yanay1** [comment]
SATURN and UCE both use the same ESM2 protein embeddings as an input.

Do you have a specific species/genome of petromyzontidae in mind? Would this work: https://useast.ensembl.org/Petromyzon_marinus/Info/Index ?

**Comment by zhonghuaxiaodangjiayo** [comment]
The URL you provided is fine.

Once again, thank you sincerely for your work!
