### ISSUE TITLE
Human lymph node AMI figure 2d

### ISSUE THREAD

**Issue by v-mahughes** [snap-stanford/UCE#21]
Could you point me to where I can find the human lymph node AMI data with UCE embeddings that was used to train the logisitic classifier in figure 2d ?

**Comment by Yanay1** [comment]
```ima_ad_lymph = ima_ad[ima_ad.obs.tissue.str.lower().str.contains("lymph")]``` 

https://drive.google.com/drive/folders/1f63fh0ykgEhCrkd_EVvIootBw7LYDVI7 the file called ima_sample.h5ad

**Comment by v-mahughes** [comment]
Do you have a terminal command I could use to download this directly onto my virtual (Linux) system?

**Comment by Yanay1** [comment]
I'm not sure exactly how to do it. This thread might help: https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive

**Comment by v-mahughes** [comment]
Do you know what the file ids are? They dont seem to be in the share links. The IMA sample is too large to transfer onto my machine manually

**Comment by Yanay1** [comment]
For ima_sample.h5ad the link is 

https://drive.google.com/file/d/16UyzyZ7jK4y5Mj0PT75vqPO68i729soq/view?usp=drive_link

So I believe the file id would be `16UyzyZ7jK4y5Mj0PT75vqPO68i729soq`

**Comment by v-mahughes** [comment]
that does not seem to work, as It downloads an html. Is there any modification from your end that allows this file to be downloaded on a remote machine? The files are too large to download then transfer manually.
