### ISSUE TITLE
IMA sample issue

### ISSUE THREAD

**Issue by v-mahughes** [snap-stanford/UCE#24]
I was able to download both files onto my system (green_monkey.h5ad and IMA_sample.h5ad). I could successfully read in green monkey data with scanpys read_h5ad function. However, when I try to read in the ima sample data with scanpy.read_h5ad I get the following error: OSError: Unable to open file (file signature not found) 

I have checked to ensure the file size matches the file size on the google drive.

**Comment by Yanay1** [comment]
That error might indicate that the file did not finish downloading properly.

**Comment by v-mahughes** [comment]
was able to download fully. In 2d i notice that not all coarse cell type annotations in the IMA lymph sample are included in the figure. Were all coarse cell types of the lymph data included in training / testing? or was the dataset restricted to those shown in the figure

**Comment by v-mahughes** [comment]
Also, the ima sample data does Not contain the UCE embeddings (no 'X_uce' layer) , but the green monkey data does.

**Comment by v-mahughes** [comment]
Or is the adata.X layer the uce embeddings? seems to be of the correct shape (1280)

**Comment by Yanay1** [comment]
For that file .X is the UCE embeddings

**Comment by v-mahughes** [comment]
would it be possible for you to provide the filtered, gene epxression matrix for this dataset as well ?

**Comment by Yanay1** [comment]
Unfortunately we don't have that for this file. Since it's collected from so many datasets, and from many different species, it would be difficult to create a corresponding gene expression dataset.
