### ISSUE TITLE
Training UCE

### ISSUE THREAD

**Issue by v-mahughes** [snap-stanford/UCE#25]
Hello, 

Does the current UCE package/scripts provided on this page have the functionality for users to train UCE on their own reference atlas ?

**Comment by Yanay1** [comment]
Since the UCE model is intended to be used as a zero shot model, we do not plan on releasing code to train the entire model. 

However, you can always train downstream models on embeddings produced by one of the base (4L or 33L) models, or set up your own finetuning / training set up.
