### ISSUE TITLE
is there training code available?

### ISSUE THREAD

**Issue by szalata** [snap-stanford/UCE#3]
I couldn't find a script used for training the model. Thanks!

**Comment by yhr91** [comment]
Technically, all the code needed from the model side to reproduce the results in the paper is available in this repository. For instance, you can take a look at the analysis scripts shared in this [repo](https://github.com/yhr91/uce_reproduce/tree/master) which only makes use of embedding produced from a pre-trained model.

The challenge you would face at the moment is not the code, but that most of our results were produced using the Tabula Sapiens v2 dataset which so far is not published.
