### ISSUE TITLE
Producing UCE embeddings for cell lines

### ISSUE THREAD

**Issue by Ontos46** [snap-stanford/UCE#34]
Hi! Apologies if that's a dumb question; I am trying to use UCE to produce embeddings for cell lines from Broad DepMap dataset but they don't have scRNA-seq data, only bulk sequencing. Can I still use the bulk RNA sequencing data to produce embeddings since all the cells in a cell line are clones so functionally they are the same? DepMap library only has TPM data for gene expressions so I wanted to make sure resulting embeddings would be valid.

**Comment by Yanay1** [comment]
You could definitely try, it would just require putting it into h5ad format first. The TPM data might have cause some issues with how we sample genes however, so I'm not sure how good the embeddings would be (the main issue is the scale could be a lot higher than for single cell data).
