### ISSUE TITLE
How to get gene embeddings

### ISSUE THREAD

**Issue by kelimeike** [snap-stanford/UCE#36]
Thank you very much for providing the UCE model! It has been a great help to me. 
I noticed that the program only provides cell embeddings for different cells in the dataset. Is there a way to also easily obtain gene embeddings corresponding to the cells?

**Comment by Yanay1** [comment]
You could use the ESM2 embedding files directly.

You can also load the model in python and then apply the `gene_embedding_layer` to those protein embeddings to get the modified smaller dimensional version that is fed into the model.

**Comment by kelimeike** [comment]
Thank you for your reply. Additionally, the README mentions a documentation file, and where can I find it?

**Comment by Yanay1** [comment]
Sorry for the confusion-- by that we meant the docstrings in the code / scripts themselves.
