### ISSUE TITLE
IMA logistic classifiers

### ISSUE THREAD

**Issue by bschilder** [snap-stanford/UCE#38]
Hi @Yanay1 , super excited to use this foundation model! Thanks for making the code and file so easy to use.

In the preprint you trained logistic classifiers on the IMA to predict the cell type identity in new datasets. I don't suppose you'd be able to share one of these pretrained classifiers for predicting cell type identity across all major cell types seen in the IMA? This would make one of the more common tasks of cell type annotation even easier.

**Comment by bschilder** [comment]
After re-reading the preprint, it seems like the logistic classifiers were only trained on specific cell types for specific use cases. Given that I need to do prediction for all cell types, I've just gone ahead and trained my own classifier. Happy to share if this is helpful.

Still might be nice to share the code for the classifiers bit of the manuscript. But i'll leave that up to you.

**Comment by yassinho-f** [comment]
> After re-reading the preprint, it seems like the logistic classifiers were only trained on specific cell types for specific use cases. Given that I need to do prediction for all cell types, I've just gone ahead and trained my own classifier. Happy to share if this is helpful.
> 
> Still might be nice to share the code for the classifiers bit of the manuscript. But i'll leave that up to you.

Hey @bschilder ,

sounds great, I am also interested in training the UCE embeddings of the IMA_sample.h5ad! Would you like to share the code?

**Comment by bschilder** [comment]
Hi @yassinho-f just through some old emails and saw this. Sorry for the long delay, here's the code:
```python
ref_path = 'data/IMA_sample.h5ad'
ref = anndata.read_h5ad(backed='r', filename=ref_path)

# Train multinomial logistic regression classifier to predict cell types from UCE embeddings
def classifier_train(ref,
                     label_key='coarse_cell_type',
                     multi_class='multinomial', 
                     solver='lbfgs', 
                     verbose=1, 
                     n_jobs=-1,
                     sample=None):
    from sklearn.linear_model import LogisticRegression

    ## randomly sample cel
    if sample is not None:
        np.random.seed(0)
        idx = np.sort(np.random.choice(ref.n_obs, sample, replace=False))
    else:
        idx = np.arange(ref.n_obs)
    # Load the UCE embeddings
    embeddings = ref.X[idx,:]
    # Load the cell types
    labels = ref.obs[label_key].astype(str).values[idx]
    # Create an instance of the LogisticRegression classifier
    classifier = LogisticRegression(multi_class=multi_class, 
                                    solver=solver, 
                                    verbose=verbose, 
                                    n_jobs=n_jobs)
    # Store label_key
    classifier.label_key = label_key
    # Fit the classifier to the UCE embeddings and cell types
    classifier.fit(X=embeddings, y=labels)
    return classifier

def classifier_predict(classifier,
                       ad, 
                       obsm_key='X_uce',
                       label_key=None):
    if label_key is None:
        label_key = classifier.label_key
    # Load the UCE embeddings
    embeddings = ad.obsm[obsm_key]
    # Predict the cell types
    predictions = classifier.predict(X=embeddings)
    # Add the predicted cell types to the anndata object
    ad.obs[label_key] = predictions
    # get the probability of each cell belonging to each class
    probs = pd.DataFrame(data=classifier.predict_proba(embeddings),
                         columns=classifier.classes_)
    return probs

```
