### ISSUE TITLE
No source information about remainder of the IMA (composed of 2.3 million cells from 28 datasets) in Extended Data Table 2 

### ISSUE THREAD

**Issue by litxiaoyao** [snap-stanford/UCE#44]
Could you please share the GSE number or publications about the 28 datasets contained in IMA for pre-training?
![屏幕截图 2024-07-15 201631](https://github.com/user-attachments/assets/1179181d-69c5-4ca7-b403-07912c4fc705)

Thanks

**Comment by litxiaoyao** [comment]
Please, it's very important for our statistic works
Thanks for your kind help

**Comment by Yanay1** [comment]
[UCE_extra_datasets_upload.csv](https://github.com/user-attachments/files/16274409/UCE_extra_datasets_upload.csv)

**Comment by litxiaoyao** [comment]
Thanks, Besides, the paper said 'The majority of IMA data (33.9 million cells and 285 datasets) is human and mouse data downloaded from CZI Cell X Gene (CxG) Census [[36](https://www.biorxiv.org/content/10.1101/2023.11.28.568918v1.full#ref-36)] version ”2023-07-10” (July 10th, 2023)', but I found CxG Census doesn't have the version ”2023-07-10”, they only provide 3 version in year 2023.
![image](https://github.com/user-attachments/assets/e043ed7c-f4a0-42b2-a820-21dcfcfd2d74)
![image](https://github.com/user-attachments/assets/90cbca16-9505-413e-ba2a-0b6dba622898)
![image](https://github.com/user-attachments/assets/326dd733-f606-498a-970b-71e053035773)
