### ISSUE TITLE
RNG and embedding stability in UCE

### ISSUE THREAD

**Issue by VictorCurean** [snap-stanford/UCE#45]
Due to the probabilistic nature of how a cell is preprocessed into a fixed size gene multiset prior to being fed into the transformer model, I was wondering if you have information about the stability of the embeddings when trying to embed the same cell multiple times. 

If I understood correctly, you are creating a multiset of size 1024 by randomly sampling without replacement from the set of expressed genes. If this is right, assuming a different seed for RNG is used, the input for the same cell will differ to some degree at each iteration. My question is if you have any information/input about how similar generated embeddings from the same cell but with different initial gene multiset are to each other. 

Thanks!

**Comment by Yanay1** [comment]
That is correct that you can get very slightly different seeds depending on sampling. Based on some experiments, this variability is very low (in other words, the embeddings for the same cell between different seeds are very similar to eachother). For the tabula sapiens benchmark for example, the standard deviation of the final scores (batch, bio and total) when running 10 batches is less than 0.003.
