### ISSUE TITLE
visualise UCE embeddings of a new dataset in the existing large graph

### ISSUE THREAD

**Issue by andykwok** [snap-stanford/UCE#46]
Is it possible to visualise UCE embeddings of a new dataset in exactly the same existing IMA embedding graph ? as illustrated in the Fig. 2a of Zero-Shot Same Representation. Thanks.

**Comment by Yanay1** [comment]
We uploaded an anndata of that IMA sample (https://github.com/snap-stanford/UCE?tab=readme-ov-file#data)

For the exact same UMAP, there are parametric versions of UMAP that you could try to use, which could maybe create that kind of visualization, but I have had trouble installing and running them before.
