### ISSUE TITLE
AnnData eval issue: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by viriditax** [snap-stanford/UCE#5]
Was trying a simple test locally on M2 MacBook, call:

python eval_single_anndata.py --adata_path chicken_heart.h5ad --dir res --species chicken

Using sample 4 layer model
**********************************
***********chicken_heart.h5ad ERROR***********
**********************************

Traceback (most recent call last):
  File "/scratch/UCE/eval_single_anndata.py", line 155, in <module>
    main(args, accelerator)
  File "/scratch/UCE/eval_single_anndata.py", line 83, in main
    processor.preprocess_anndata()
  File "/scratch/UCE/evaluate.py", line 93, in preprocess_anndata
    self.adata, num_cells, num_genes = \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

This is after successful download of model:

Downloading ./model_files/species_chrom.csv from https://figshare.com/ndownloader/files/42706558 ...

100%|█████████████████████████████████████| 4.10M/4.10M [00:00<00:00, 4.27MiB/s]
Downloading ./model_files/species_offsets.pkl from https://figshare.com/ndownloader/files/42706555 ...

100%|█████████████████████████████████████████| 139/139 [00:00<00:00, 22.3kiB/s]
Downloading resmodel_files/protein_embeddings.tar.gz from https://figshare.com/ndownloader/files/42715213 ...

100%|█████████████████████████████████████| 2.74G/2.74G [02:19<00:00, 19.7MiB/s]
Done!
Downloading ./model_files/all_tokens.torch from https://figshare.com/ndownloader/files/42706585 ...

100%|█████████████████████████████████████| 2.98G/2.98G [02:31<00:00, 19.7MiB/s]
Using sample 4 layer model
Downloading ./model_files/4layer_model.torch from https://figshare.com/ndownloader/files/42706576 ...

100%|█████████████████████████████████████| 3.40G/3.40G [02:57<00:00, 19.2MiB/s]

Same issue with some previously prepared AnnData objects from human samples with species set to human.

**Comment by Yanay1** [comment]
What is the terminal output when you try to embed a human dataset?

**Comment by Yanay1** [comment]
Can you please post the full terminal output? There should be terminal output before the error. What are the gene names in .var_names? Are they gene names or ensembl IDs?

**Comment by yhr91** [comment]
Did you also just try `python eval_single_anndata.py` with no additional arguments? That downloads and runs the default h5ad and would establish if it's an environment issue or something else

**Comment by yhr91** [comment]
Thanks for pointing this out. We made some updates to the code for running cross species data

If you follow the instruction in this [notebook](https://github.com/snap-stanford/UCE/blob/main/data_proc/Create%20New%20Species%20Files.ipynb) it should get everything set up correctly to run the script.

We're working on simplifying the interface a bit more for the cross species setting

**Comment by yhr91** [comment]
Thanks, can you share the exact command you are using for running evaluation on the human dataset

**Comment by Yanay1** [comment]
Could you please try pulling the latest version of the repo and running the default command again? Thanks!

**Comment by Yanay1** [comment]
I'm not sure exactly what this issue might be. It could be that that file did not unzip or download properly? Maybe try downloading it again?
