### ISSUE TITLE
 IMA sample dataset missing X_uce embeddings

### ISSUE THREAD

**Issue by xqiu625** [snap-stanford/UCE#50]
I'm working with the IMA sample dataset provided (IMA_sample.h5ad), and I've noticed that it doesn't contain the 'X_uce' embeddings in the .obsm attribute as expected. Here's what I see when I print the AnnData object:

``` python
>>> print(ima_adata)
AnnData object with n_obs × n_vars = 2969114 × 1280
    obs: 'cell_type', 'tissue', 'idx', 'dataset', 'species', 'coarse_cell_type'
    uns: 'cell_type_gpt_colors', 'coarse_cell_type_yanay_colors', 'dataset_colors', 'neighbors', 'pca', 'species_colors', 'tissue_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
```
As you can see, the .obsm attribute contains 'X_pca' and 'X_umap', but not 'X_uce'. This makes it challenging to use the IMA sample for zero-shot cell type classification.

**Comment by Yanay1** [comment]
Hello, for this anndata the UCE values are in the X slot.
