### ISSUE TITLE
Questions about average running time

### ISSUE THREAD

**Issue by HelloWorldLTY** [snap-stanford/UCE#9]
Hi, I am using a cluste with one rtx3090 gpu, but the running time for the demo dataset seems very strange. It seems that some people used only macbook with M1 chip and successfully run the demo case, but I need quite long time here:

![image](https://github.com/snap-stanford/UCE/assets/43333475/4c0564a0-8ce8-4a79-bfcc-738f57f7b646)

Is it possible for me to know the reason? What is the expected running time for demo dataset using for exmaple, one A100 GPU? Thanks.

**Comment by Yanay1** [comment]
That definitely seems slower than it should be-- can you check if the GPU is being used? It could be that it is running on CPU instead of gpu. On an A100 (80GB) it takes less than 5 minutes to embed the demo dataset.

**Comment by HelloWorldLTY** [comment]
Thanks, but I install all of the pacakges based on the instructions. I will try and get back to you.

**Comment by HelloWorldLTY** [comment]
Thanks a lot. It seems work well now.
![image](https://github.com/snap-stanford/UCE/assets/43333475/78f68db2-f0d8-410e-9de9-e93d4a493b08)

I think the problem is caused by installing the accelerate package via conda rather than pip. Would you please add this package to the requirement.txt file? Thanks.

**Comment by Yanay1** [comment]
Good catch! I updated the requirements to include accelerate (rather than accelerator).
